// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP4tMz8jn7Xyb1djzxMO0zrAzYgArt-lA',
    appId: '1:222295396870:web:0ac14d743d64b1b92ea987',
    messagingSenderId: '222295396870',
    projectId: 'careerpilot-ai-a5b1f',
    authDomain: 'careerpilot-ai-a5b1f.firebaseapp.com',
    storageBucket: 'careerpilot-ai-a5b1f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd_Pjm1ZgEXmVRFI8e-xWv8ZQjJE-Dn-c',
    appId: '1:222295396870:android:f927065050ac5b822ea987',
    messagingSenderId: '222295396870',
    projectId: 'careerpilot-ai-a5b1f',
    storageBucket: 'careerpilot-ai-a5b1f.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAP4tMz8jn7Xyb1djzxMO0zrAzYgArt-lA',
    appId: '1:222295396870:web:f9dc70b929d5dac82ea987',
    messagingSenderId: '222295396870',
    projectId: 'careerpilot-ai-a5b1f',
    authDomain: 'careerpilot-ai-a5b1f.firebaseapp.com',
    storageBucket: 'careerpilot-ai-a5b1f.firebasestorage.app',
  );
}
